### ISSUE TITLE
Rationale details for CIP-107

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/CIPs#108]
It's a good idea to burn storage collateral when defunding to mitigate inflation of CFX tokens. However, rationale details are currently missed for CIP-107. For example, 

- The estimation of the transaction fee growth. This is important for developers and users.
- The estimation of the inflation rate change. This can guide DAO to decided *p*.
- Why the minimal *p* but not zero is choosen as _0.25_, and won't this value greatly increase the transaction fee? 

I hope these details could be added to the next version of CIP-107

**Comment by ChenxingLi** [comment]
The original design of CIP-107 has been replaced.
