### ISSUE TITLE
Discussion: Conflux address improvement

### ISSUE THREAD

**Issue by bytelaw** [Conflux-Chain/CIPs#37]
**Motivation**：Avoid the use of Ethereum and conflux addresses misdirection

**scheme**：
1. Wrapper current hex address to base58 format like TRON
2. Maybe let conflux support the base58 and hex format or only one format.

**Comment by Thegaram** [comment]
Please note that most Ethereum addresses are not valid Conflux addresses, thought most (all?) valid Conflux addresses are indeed valid Ethereum addresses. In Conflux, addresses have a type prefix:

```
0x1... ~ user account      e.g. 0x163b0cfafa4db0a4a455d7128f0117c69c021d8c
0x8... ~ contract account  e.g. 0x8a4a948c16a509a30551680bcbe99220f4f64f04
0x0... ~ internal contract e.g. 0x0888000000000000000000000000000000000000
```

See section 3.1 of the [protocol specification](https://confluxnetwork.org/files/Conflux_Protocol_Specification_20201020.pdf).

Tools (e.g. Conflux Portal) are expected to know this and reject invalid addresses, thought admittedly there is room for confusion, especially when it comes to cross-chain operations. I think at this point it is more of a UX issue, e.g. dapps should prefer wallet popup instead of manual address input, add warnings, etc.

**Comment by bytelaw** [comment]
Yeah, i know,  But many general user always misdirection with Ethereum address and Conflux address, some people lose money by this misunderstand.

**Comment by fanlong** [comment]
Although this might be backward compatible given our current standard, it affects many interfaces and decentralized applications. @Thegaram could you wrap this as a CIP for our roadmap discussion?

**Comment by Thegaram** [comment]
Alternative proposal from @Pana:

Conflux is using EIP-55 checksum addresses. We could slightly modify the algorithm to arrive at a similar checksum mechanism, but one which is not compatible with Ethereum's. For instance:

```diff
-hashed_address = eth_utils.keccak(text=hex_addr).hex()
+hashed_address = eth_utils.keccak(text=`conflux${hex_addr}`).hex()
```

Conflux nodes do not verify checksum addresses, only tools like Portal, Conflux Studio, and solc do. As a result, the cost of update is much smaller; there is no hardfork needed, and the tools can decide until what time they want to support legacy checksum addresses.

The main issue here is `solc`, as it is not maintained by Conflux. If we keep using Ethereum's version, it will reject compiling contracts that contain new checksum addresses.

**Comment by Thegaram** [comment]
After some discussion, we decided on using a base32-encoded address similar to Bitcoin Cash \[[link](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md)\]. Below is a draft of the encoding algorithm for discussion:

# Base32 address

This section defines conversion between the following address types:

- **conflux-hex-address**: a valid, 20-byte, type-prefixed Conflux hex address, e.g. `0x106d49f8505410eb4e671d51f7d96d2c87807b09`.

TODO: list type prefixes, mention checksum, link spec

- **conflux-base32-address**: a network- and type-prefixed Conflux base32 address, e.g. `cfx:user:0086ujfsa1a11uuecwen3xytdmp8f03v140ypk3mxc`

## Encoding

INPUT: a conflux-hex-address (20 bytes) and a network-id (4 bytes)
OUTPUT: a conflux-base32-address

1. Derive the network-prefix:

```
    match network-id:
        case 1029: "cfx"
        case 1:    "cfx-test"
        case n:    "cfx-[n]"
```

Examples of valid network-prefixes: `"cfx"`, `"cfx-test"`, `"cfx-17"`
Examples of invalid network-prefixes: `"bch"`, `"cfx-1029"`, `"conflux"`

2. Derive the type-prefix:

```
    match addr[0] & 0xf0
        case b00000000: "builtin"
        case b00010000: "user"
        case b10000000: "contract"
```

Examples of valid prefixes: `"builtin"`, `"user"`, `"contract"`
Examples of invalid prefixes: `"internal"`

3. Derive the version-byte:

The version-byte has the bits `"xyyyyzzz"`, where:
- `x`: reserved `b0`
- `yyyy`: type
```
    mainnet:     b0000
    not-mainnet: b0001
```
- `zzz`: hash length (for compatibility), see: [BCH spec](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#version-byte)

4. Base32-encode payload:

To create the payload, first concatenate the version-byte with the input address to get a 21-byte array.
Then, encode it left-to-right, mapping each 5-bit sequence to the corresponding character (see alphabet below).
Pad to the right with zero bits to complete any unfinished chunk at the end (in this case, b00).
In our case, 21-byte payload + 2 bit 0-padding will result in a 34-byte base32-encoded string.

We use the following alphabet: `0123456789abcdefghjkmnprstuvwxyz` (`o`, `i`, `l`, `q` removed).

```
0x00 => 0    0x08 => 8    0xa6 => g    0xb4 => s
0x01 => 1    0x09 => 9    0xa7 => h    0xb5 => t
0x02 => 2    0xa0 => a    0xa8 => j    0xb6 => u
0x03 => 3    0xa1 => b    0xa9 => k    0xb7 => v
0x04 => 4    0xa2 => c    0xb0 => m    0xb8 => w
0x05 => 5    0xa3 => d    0xb1 => n    0xb9 => x
0x06 => 6    0xa4 => e    0xb2 => p    0xc0 => y
0x07 => 7    0xa5 => f    0xb3 => r    0xc1 => z
```

5. Calculate checksum:

    TODO: add https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#checksum

6. Finalize:

    Concatenate the following parts to get the final address: `[network-prefix]`, `":"`, `[type-prefix]`, `":"`, `[payload]`, `[checksum]`

Example:

INPUT: `0x106d49f8505410eb4e671d51f7d96d2c87807b09`, `1029`

    [0x10, 0x6d, 0x49, 0xf8, 0x50, 0x54, 0x10, 0xeb, 0x4e, 0x67, 0x1d, 0x51, 0xf7, 0xd9, 0x6d, 0x2c, 0x87, 0x80, 0x7b, 0x09]
    1. network-prefix: 1029 => "cfx"
    2. type-prefix: 0x10 & 0xf0 == b00010000 => "user"
    3. version-byte: 0x00
    4. payload: [0x00, 0x10, 0x6d, 0x49, 0xf8, 0x50, 0x54, 0x10, 0xeb, 0x4e, 0x67, 0x1d, 0x51, 0xf7, 0xd9, 0x6d, 0x2c, 0x87, 0x80, 0x7b, 0x09]
       5-bit parts: [0x00, 0x00, 0x08, 0x06, 0x1a, 0x12, 0x0f, 0x18, 0xa, 0x1, 0xa, 0x1, 0x1, 0x1a, 0x1a, 0xe, 0xc, 0x1c, 0xe, 0x15, 0x03, 0x1d, 0x1e, 0x19, 0x0d, 0x14, 0x16, 0x08, 0x0f, 0x00, 0x03, 0x1b, 0x01, 0x04]
       base32-encoded: "0086ujfsa1a11uuecwen3xytdmp8f03v14"
    5. base32-encoded checksum: "0ypk3mxc"
    6. concatenated result: "cfx:user:0086ujfsa1a11uuecwen3xytdmp8f03v140ypk3mxc"

**Comment by Thegaram** [comment]
## Decoding (Draft)

INPUT: a conflux-base32-address
OUTPUT: a conflux-hex-address (20 bytes) and a network-id (4 bytes)

1. Split at `":"` into 3 parts `network-prefix-raw`, `type-prefix`, `payload-raw` or reject.

TODO: make `type-prefix` optional?

2. Parse network-id:

```
    match network-prefix-raw
        case "cfx":      1029
        case "cfx-test": 1
        case "cfc-[n]":  n if n fits into 4 bytes, otherwise reject
        otherwise:       reject
```

3. Parse type-prefix:

    - If `type-prefix` is NOT one of `"builtin"`, `"user"`, `"contract"`, reject.

4. Validate payload:

    - If payload contains both lowercase and uppercase characters, reject.
    - If payload contains invalid characters (not in the alphabet), reject.

5. Decode `payload-raw` into 5-bit array using the alphabet.

6. Validate checksum.

    TODO

7. Convert `payload-raw` into 8-bit array, split into `version-byte` and `payload`.

8. Validate payload length.

    TODO

8. Validate network-id:

    - If `version-byte & b01111000` is `b00000000` and network-id is NOT `1029`: reject
    - If `version-byte & b01111000` is `b00001000` and network-id is `1029`: reject

9. Validate type-id:

    - If `payload[0] & 0xf0` is `b00000000` and type-prefix is NOT `"builtin"`: reject.
    - If `payload[0] & 0xf0` is `b00010000` and type-prefix is NOT `"user"`: reject.
    - If `payload[0] & 0xf0` is `b10000000` and type-prefix is NOT `"contract"`: reject.

Return `(payload, network-id)`.

**Comment by Thegaram** [comment]
The spec has been finalized in [CIP-37](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-37.md).

**Comment by ysqi** [comment]
首先，我双手赞同使用 base32编码address，这个在我我刚进入Conflux技术群时便建议使用base32和checksum，现在推进还不算晚。

base32-checksum 技术的首要目的是解决因地址输入性错误而遭受损失。

但新规则中较特殊的几点，我有不同看法：
1. 标识符中加入了连接符`:`：这个的必要性在哪里？
2.  `network-prefix`:  非常鸡肋的设计，反而加入了复杂性，不管是钱包、SDK、WEB端、后端 在处理地址相关时都需要多考虑一个因子。对于用户来也非常具有迷惑性，“为何我同一个钱包，怎么突然有时候是A地址，有时候确是B?”。同样，开发人员在开发测试过程中，明明是同一个私钥具有确定性的地址，但会因测试环境的不同(chainid 变化)，而不得不动态计算地址。

我的建议是更简单化，地址编码格式是：`<Chain Flag><address type><payload><checksum>`:
1. `<Chain flag>`: 固定为 'cfx’,占三个字符。联盟链可以自定义，但长度必须为3。
2. `<address type>`: 地址类型，占一个字符。 
           - 1-外部地址（通过私钥创建的钱包）；
           - 8-合约地址（部署新合约时生成）。
3. `<payload>`: 地址hex值得 base32 编码。
4. `<checksum>`: 地址校验码，涵盖`<Conflux Flag><Address Type><payload>`。

**Comment by yangzhe1990** [comment]
> 首先，我双手赞同使用 base32编码address，这个在我我刚进入Conflux技术群时便建议使用base32和checksum，现在推进还不算晚。
> 
> base32-checksum 技术的首要目的是解决因地址输入性错误而遭受损失。
> 
> 但新规则中较特殊的几点，我有不同看法：
> 
> 1. 标识符中加入了连接符`:`：这个的必要性在哪里？
这部分主要借鉴了bitcoincash的设计。如果用微信扫描metamask生成的ETH地址的QR码你会发现前面有个ethereum:前缀。其实大家都在这么做了。

The connector char ':' is a design we borrowed from bitcoincash. This is already a common practice. You can also find the address QR code generated by metamask has a "ethereum:" prefix.

> 2. `network-prefix`:  非常鸡肋的设计，反而加入了复杂性，不管是钱包、SDK、WEB端、后端 在处理地址相关时都需要多考虑一个因子。对于用户来也非常具有迷惑性，“为何我同一个钱包，怎么突然有时候是A地址，有时候确是B?”。同样，开发人员在开发测试过程中，明明是同一个私钥具有确定性的地址，但会因测试环境的不同(chainid 变化)，而不得不动态计算地址。

eth开发者经常犯的错误是不小心在测试的过程中，把昂贵的资产打到main net地址。这种失误在脚本环境下尤其不可控。当你的脚本遇到地址错误的时候，它已经帮助你避免了昂贵的资产损失。

A common misfortune ethereum developer hits is that when they test their dapp in testnet, they by accident send valuable assets onto main-net. This is especially hard to notice in scripts. When you hit such address network mismatch error in your script, the asset loss are prevented from happening.
> 
> 我的建议是更简单化，地址编码格式是：`<Chain Flag><address type><payload><checksum>`:
> 
> 1. `<Chain flag>`: 固定为 'cfx’,占三个字符。联盟链可以自定义，但长度必须为3。
> 2. `<address type>`: 地址类型，占一个字符。
>    - 1-外部地址（通过私钥创建的钱包）；
>    - 8-合约地址（部署新合约时生成）。
> 3. `<payload>`: 地址hex值得 base32 编码。
> 4. `<checksum>`: 地址校验码，涵盖`<Conflux Flag><Address Type><payload>`。
